---
title: Junior Usca
email: junior.usca@gmail.com
phone: "(+51) 935 088 511"
address: |
  Arequipa - Perú
  J.L.B. y Ribero
twitter_username: 
facebook_username: junior.usca
github_username: juniorUsca
description: |
  Mi blog personal en español sobre lo que hago en mis estudios y en mi trabajo.
url: https://juniorusca.github.io
baseurl: ''
encoding: utf-8
timezone: America/Lima
markdown: kramdown
theme: jekyll-theme-editorial
paginate: 6
paginate_first_path: "/blog/"
paginate_path: "/blog/page:num/"
image: https://juniorusca.github.io/images/default.jpg
disqus:
  shortname: juniorusca
google_analytics: UA-99605040-1
tag_page_layout: tag_page
tag_page_dir: tag
tag_permalink_style: pretty
gems:
- jekyll-feed
- jekyll-paginate
- jekyll-auto-image
- jekyll-sitemap
exclude:
- Gemfile
- Gemfile.lock
- html5up-editorial
