---
title: Junior Usca
email: junior.usca@gmail.com
phone: "(+51) 935 088 511"
address: |
  Arequipa - Perú
  J.L.B. y Ribero
twitter_username: 
facebook_username: junior.usca
github_username: juniorUsca
description: |
  Write an awesome description for your new site here. You can edit this line in _config.yml. It will appear in your document head meta (for Google search results) and in your feed.xml site description.
baseurl: ''
url: https://juniorusca.github.io/
encoding: utf-8
timezone: America/Lima
markdown: kramdown
theme: jekyll-theme-editorial
paginate: 3
paginate_first_path: "/blog/"
paginate_path: "/blog/page:num/"
image: https://juniorusca.github.io/images/default.jpg
gems:
- jekyll-feed
- jekyll-paginate
- jekyll-auto-image
exclude:
- Gemfile
- Gemfile.lock
- html5up-editorial
